name: Build Docker Image
on:
    push:
        branches:
            - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Verify Repository
        run: ls -R

      - name: Build Docker Image
        run: |
          cd app
          docker build -t fastapi-app .